### ISSUE TITLE
window is not defined with nuxt in ssr mode

### ISSUE THREAD

**Issue by kconde2** [EO2875/vue-formulate-select#13]
![window is not defined](https://user-images.githubusercontent.com/43377621/177438460-61651911-5440-4083-952a-46e67fdde306.png)

**Comment by Banzai** [comment]
in nuxt.config.js  ` { src: '~/plugins/Formulate-select', ssr: false },`

**Comment by kconde2** [comment]
I was also able to use `ssr: false` in `nuxt.config.js` to make it works.

Thanks for you answer.
