### ISSUE TITLE
vue-select.css dependency was not found

### ISSUE THREAD

**Issue by realnot** [EO2875/vue-formulate-select#6]
ERROR  Failed to compile with 1 error                                                                                                                                                                       

This dependency was not found:

* vue-select/dist/vue-select.css in ./src/main.js

To install it, you can run: npm install --save vue-select/dist/vue-select.css

**Comment by EO2875** [comment]
README updated in [commit bc452](https://github.com/EO2875/vue-formulate-select/commit/bc4524d06d40d719ed7ecfde1fcdb51fba80b47c)
