### ISSUE TITLE
Documentation is not up to date

### ISSUE THREAD

**Issue by mattkaye** [EO2875/vue-formulate-select#8]
I couldn't get the select input to render until I added these two props:
```
type="select"
data-type="vue-select"
```

Hope this helps others.

**Comment by EO2875** [comment]
So are you doing something like:

```html
<FormulateInput
    type="select"
    data-type="vue-select"
    :options="[
        {value: 'MX', label: 'Mexico'},
        {value: 'TH', label: 'Thailand'},
        {value: 'BI', label: 'Burundi'},
    ]"
/>
```

**Comment by freetimeSPB** [comment]
I also can render vue-select, when i'm using type="select" - it's rendering usual select from vueformulate

**Comment by EO2875** [comment]
You have to use `type="vue-select"`

(These instructions are on the README file under "Usage", but it's easy to miss.)
